### ISSUE TITLE
Something wen wrong! Open an issue at ... Fetch to user error

### ISSUE THREAD

**Issue by evandrocoan** [kurt-liao/so-stats#21]
![image](https://user-images.githubusercontent.com/5332158/213835802-f8ed4e91-a307-469d-93bc-3d2611c46575.png)

**Comment by evandrocoan** [comment]
It is working again now.

**Comment by kurt-liao** [comment]
@evandrocoan Thanks for notice. The api sometimes went wrong, but I am not figure out why. I'll keep tracking. Anyway, thanks.
