### ISSUE TITLE
feat: Support i18n

### ISSUE THREAD

**Issue by kurt-liao** [kurt-liao/so-stats#6]

**Comment by natastro** [comment]
Hello! I'm happy to provide Spanish translations if needed. 😃

**Comment by kurt-liao** [comment]
@natastro Hi, it's so glad to hear this. And also it's very welcome to help me to do this work.

I've assigned you in this issue, and thanks 😃! Anyway, happy hacking!

**Comment by natastro** [comment]
Hi @kurt-liao - I just wanted to know what file has the i18n strings that should be translated? Thank you again!! 😀

**Comment by kurt-liao** [comment]
> Hi @kurt-liao - I just wanted to know what file has the i18n strings that should be translated? Thank you again!! grinning

translation file is in [src/translation.js](https://github.com/kurt-liao/so-stats/blob/main/src/translation.js)
